# Generated by Django 4.2.2 on 2023-08-16 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=4000)),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_url', models.URLField(blank=True)),
                ('Winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lists', to='auctions.categories')),
                ('listed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
