# Generated by Django 4.2.2 on 2023-08-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='watching_users', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
