# Generated by Django 4.2.2 on 2023-08-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bidding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bidding',
            new_name='Biddings',
        ),
    ]
